name: Github Action №1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-html flake8-html
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#    - name: Lint with flake8
#      run: |
#        flake8 . --format=html --htmldir=reports/flake-report
    - name: Test with pytest
      run: |
        pytest --html=reports/pytest-html/report.html --self-contained-html
    - name: Upload reports
      run: |
        git config --global user.email "roshen@zebanda.com"
        git config --global user.name "Petro"
        git add . && git commit -m "Add reports"
        git push
